typography_spectrum: 0.6096578540746123
color:
  brandStrength: 0.021611374570056796
  lightness: 0.7319474807009101
  saturation: 0.7686384920962155
  rhythmicContrast: 0.6179553417023271
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.13913944317027926
analytics:
  google: UA-111724558-1
  twitter: '@youmustdo1'
author:
  email: youmustdo1@gmail.com
  name: youmustdo
  url: 'https://thegrid.ai/youmustdo'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/65880a7b-750d-4a48-af2c-425840050bdc.png
name: youmustdo
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Follow our twitter
    url: 'https://twitter.com/youmustdo1'
    type: external
  - name: About us
    id: cb56b9dd-a8c2-421d-ae1e-cb9376e4ab5b
    type: content
  - name: Advertising
    id: c2a9963d-9c30-4fa9-86f8-71a78b095490
    type: content
  - name: 'Copyright © 2018 -https://thegrid.ai/youmustdo- All rights reserved.'
    id: 7ac473a8-06dc-4b42-8b85-a87b6982ffd8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6c32e92-d734-4378-acc4-d517a8ceefef.png
title: You must do
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/894a9bd8-d838-489a-81f5-97cf66b4fd3a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/894a9bd8-d838-489a-81f5-97cf66b4fd3a.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Things you must do but maybe never do. Scroll down you'll be shocked!
purpose:
  - type: contact
    url: 'mailto:youmustdo1@gmail.com'
    label: Contact us for any suggestion
  - type: external
    url: 'https://twitter.com/youmustdo1'
    label: Follow us on Twitter
