typography_spectrum: 0.6096578540746123
color:
  brandStrength: 0.021611374570056796
  lightness: 0.7319474807009101
  saturation: 0.7686384920962155
  rhythmicContrast: 0.6179553417023271
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.13913944317027926
analytics:
  google: UA-111724558-1
  twitter: '@youmustdo1'
author:
  email: youmustdo1@gmail.com
  name: youmustdo
  url: 'https://thegrid.ai/youmustdo'
name: youmustdo
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: You must do
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/282bf4be-b131-4e55-bd63-1a0c5785c87c.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/282bf4be-b131-4e55-bd63-1a0c5785c87c.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Things you must do but maybe never do. Scroll down you'll be shocked!
purpose:
  - type: contact
    url: 'mailto:youmustdo1@gmail.com'
    label: Contact us for any suggestion
